Fix zh readme for installation
Bill-Haku/kawaii-gcc pull request #12
Opened 2023-11-23 13:47 UTC by dabao1955

2023-11-23 13:58 UTC, Bill-Haku requested changes

2023-11-23 13:58 UTC, Bill-Haku commented on README-zh.md
> +    ./merge-zh.sh
仓库里自带的`gcc-zh.po`已经跑过一遍那个脚本了，应该不用再跑一遍吧

2023-11-23 14:13 UTC, dabao1955 commented on README-zh.md
> +    ./merge-zh.sh
在上述指令中，gcc-zh.po文件只被处理了一次，就是在运行./merge-zh.sh的时候。这个脚本的作用是将kawaii-gcc项目中的gcc-zh.po文件和GCC官方的gcc-zh.po文件合并，生成一个新的gcc-zh.po文件，包含了GCC的所有中文信息和kawaii-gcc的一些可爱的信息。这个新的gcc-zh.po文件会覆盖原来的gcc-zh.po文件。根据#11的描述，只需要修改kawaii-gcc的文件就可以了。所以鄙人的拙见认为应该删除仓库根目录中的gcc-zh.po

2023-11-23 14:35 UTC, Bill-Haku commented on README-zh.md
> +    ./merge-zh.sh
你前面说的都没问题。所以现在仓库里已有的`gcc-zh.po`文件是已经被合并处理过的，如果只是第一次试用的话就不需要重新合并一次了。而`src`中的文件是为了方便修改用的，如果不修改就不需要管这个文件夹。然后我打算在README中再加一段关于如何修改的部分。如果你们有谁愿意PR就PR，没有就我来写。

2023-11-23 14:45 UTC, dabao1955 commented on README-zh.md
> +    ./merge-zh.sh
> 你前面说的都没问题。所以现在仓库里已有的`gcc-zh.po`文件是已经被合并处理过的，如果只是第一次试用的话就不需要重新合并一次了。而`src`中的文件是为了方便修改用的，如果不修改就不需要管这个文件夹。然后我打算在README中再加一段关于如何修改的部分。如果你们有谁愿意PR就PR，没有就我来写。

如果不同步的话怎么办？

2023-11-23 15:30 UTC, Bill-Haku commented on README-zh.md
> +    ./merge-zh.sh
PR时检查是否合并了文件保存到`gcc-zh.po`中。即使没有同步，那也就是最新的修改没有加进去而已，不是什么大问题。不提供编译好的文件是因为我不确定各个版本和各个发行版中msgfmt编译的二进制文件能否通用。

2023-11-24 04:19 UTC, dabao1955 commented on README-zh.md
> +    ./merge-zh.sh
> PR时检查是否合并了文件保存到中。即使没有同步，那也就是最新的修改没有加进去而已，不是什么大问题，参考更新后的README应该可以很快发现问题。不提供编译好的文件是因为我不确定各个版本和各个发行版中msgfmt编译的二进制文件能否通用。`gcc-zh.po`

根据以下信息我认为应该是通用的:
```
user@localhost ~> aptitude show gcc-12-locales
软件包：gcc-12-locales
版本号：12.2.0-14
新: 是
状态: 已安装
自动安装: 否
优先级：可选
部分：devel
维护者：Debian GCC Maintainers <debian-gcc@lists.debian.org>
体系：all
未压缩尺寸：12.7 M
依赖于: gcc-12-base (>= 12), cpp-12 (>= 12)
推荐: gcc-12 (>= 12)
描述：GCC, the GNU compiler collection (native language support files)
 Native language support for GCC. Lets GCC speak your language, if translations are available.

 Please do NOT submit bug reports in other languages than "C". Always reset your language settings to use
 the "C" locales.
主页：http://gcc.gnu.org/


user@localhost ~> file kawaii-gcc/gcc.mo
kawaii-gcc/gcc.mo: GNU message catalog (little endian), revision 0.0, 4189 messages, Project-Id-Version: gcc 13.1-b20230409
```

2023-11-24 06:40 UTC, Bill-Haku commented on README-zh.md
> +    ./merge-zh.sh
既然如此，也可以考虑提供编译好的`mo`文件。

2023-11-24 08:19 UTC, Bill-Haku commented
可以，但是`mo`文件没有放进来啊。我之前写在gitignore里面了，你一并把这个加进来吧

2023-11-24 08:22 UTC, Bill-Haku approved these changes
LGTM. thx

2023-11-24 08:23 UTC, merged

2023-11-24 08:24 UTC, Bill-Haku commented
草你怎么改draft了我还以为是我刚才点错了

2023-11-24 08:24 UTC, dabao1955 commented
？

2023-11-24 08:26 UTC, Bill-Haku commented
你还有什么要改的吗

2023-11-24 08:29 UTC, dabao1955 commented
> 你还有什么要改的吗

~~主要是根目录的gcc-zh.po没来得及删~~

2023-11-24 08:40 UTC, Bill-Haku commented
哎这个问题不大，先留在这，万一那些从视频过来的人没读readme就照着视频做又发现有问题